# These are supported funding model platforms

github: TranHuuDat2004


| **Chuyển khoản qua VietQR** | Quét mã QR dưới đây bằng ứng dụng ngân hàng của bạn. |
| --- | --- |
| | ![VietQR Donate](https://img.vietqr.io/image/VCB-1031355714-compact2.png?addInfo=Donate%20ANIME.TV&accountName=TRAN%20HUU%20DAT) |

